version: 2.1

jobs:
    buildPhp74:
        docker:
            -   image: circleci/php:7.4-node-browsers
        working_directory: ~/regular
        steps:
            - checkout
            -   run: sudo composer self-update
            -   restore_cache:
                    keys:
                        - composer-v1-{{ checksum "composer.lock" }}
            -   run: composer install -n --dev
            -   save_cache:
                    key: composer-v1-{{ checksum "composer.lock" }}
                    paths:
                        - vendor
            -   run: ./runTests.sh

workflows:
    version: 2
    regular_workflow:
        jobs:
            - buildPhp74
